name: Create Release
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  release:
    uses: batinicaz/gha/.github/workflows/release.yml@496ea41524e0a8cd55a996b721f6854c4c206b1d # ratchet:batinicaz/gha/.github/workflows/release.yml@v1.2.10
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
