name: Pre-commit Cache
on:
  push:
    branches: [main]
    paths: [".pre-commit-config.yaml"]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: batinicaz/gha/.github/actions/pre-commit@v1
